drop table if exists categories;
drop table if exists events;
drop table if exists users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255) UNIQUE                     NOT NULL,
    email VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT pk_user_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT pk_category_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    annotation        VARCHAR(2000)                           NOT NULL,
    category_id       BIGINT                                  NOT NULL,
    description       VARCHAR(7000)                           NOT NULL,
    eventDate         VARCHAR(32)                             NOT NULL,
    paid              BOOLEAN,
    participantLimit  BIGINT,
    requestModeration BOOLEAN,
    title             VARCHAR(120)                            NOT NULL,
    state             VARCHAR(32),
    lat               FLOAT                                   NOT NULL,
    lon               FLOAT                                   NOT NULL,
    CONSTRAINT pk_event_id PRIMARY KEY (id),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories (id)
);
