version: '3.1'
services:
  stats-server:
    build: stat-service/stat-server
    container_name: stats
    image: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    restart: always
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://stats-db:5432/stats-db
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=password
      - TZ=GMT

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=GMT

  ewm-service:
    build: ewm-service
    container_name: ewm
    image: ewm
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    restart: always
    environment:
      - STAT_SERVER_URL=http://stats:9090
      - SPRING_R2DBC_URL=r2dbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=password
      - TZ=GMT

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=GMT